admin/urls.py
from django.urls import path
from . import views


urlpatterns = [
    
]

miniblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/',include('admin.urls')),
    path('',include('user.urls')),

]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path('index',views.index, name='index'),
    path('',views.login, name='login'),
    path('logout',views.logout, name='logout'),
    path('add_blog',views.add_blog, name='add_blog'),
    path('edit_profile',views.edit_profile, name='edit_profile'),
    path('change_password',views.change_password, name='change_password'),
    path('comment/<int:idd>',views.comment, name='comment'),
    path('view_comment/<int:idd>',views.view_comment, name='view_comment'),







]

admin/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    

class Account(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    type = models.CharField(max_length=100, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


class Blog(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    description = models.CharField(max_length=10000)
    image = models.ImageField(upload_to='blogs/')
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null= True)



class Comments(models.Model):
    comments = models.CharField(max_length=3000)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)

admin/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.shortcuts import render, redirect
from user.models import User, Account, Blog, Comments

# Create your views here.


def index(request):
    object = Blog.objects.all()
    obj = Account.objects.get(user_id = request.session['userid'])
    return render(request,'index.html',{'data':obj, 'objects':object})



def login(request):
    msg = ""
    if request.method =="POST":
        if 'u_register' in request.POST:
            name = request.POST['Name']
            email = request.POST['Email']
            password = request.POST['Password']
            username = request.POST['Username']
            username_exist = Account.objects.filter(username = username).exists()
            if not username_exist:
                obj = User(name = name, email = email)
                obj.save()
                account = Account(username = username, password = password, type = 'user', user_id = obj.id )
                account.save()
            else:
                msg = 'username already exist'

        if 'u_login' in request.POST:
            login_username = request.POST['username']
            login_password = request.POST['password']
            try:
                object = Account.objects.get(username = login_username, password = login_password)
                request.session['userid'] = object.id
                return redirect('user:index')
            except:
                return render(request,'login.html',{'message':'invalid username or password'})

    return render(request,'login.html',{'error_msg':msg})


def logout(request):
    del request.session['userid']
    return redirect('user:login')


def add_blog(request):
    if request.method == "POST":
        title = request.POST['title']
        subtitle = request.POST['subtitle']
        description = request.POST['description']
        image = request.FILES['image']

        obj = Blog(title = title, subtitle = subtitle, description = description, image = image, user_id = request.session['userid'])
        obj.save()

    return render(request,'add_blog.html')



def edit_profile(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        username = request.POST['username']

        obj = Account.objects.get(id = request.session['userid'])
        User.objects.filter(id = obj.user_id).update(name = name, email = email)
        # Account.objects.filter(id = request.session['userid']).update(username = username)
        username_exist = Account.objects.filter(username = username).exists()
        if not username_exist:
            Account.objects.filter(id = request.session['userid']).update(username = username)

        else:
            msg = 'username already exist'


    obj = Account.objects.get(user_id = request.session['userid'])
    return render(request,'edit_profile.html',{'data':obj})




def change_password(request):
    message = ""
    msg = ""
    mess = ""
    if request.method == "POST":
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        obj = Account.objects.get(id = request.session['userid'])
        if obj.password == current_password:
            if new_password == confirm_password:
                Account.objects.filter(id = request.session['userid']).update(password = confirm_password)
                mess = "Your password changed successfully"
            else:
                message = 'please confirm new password'
        else:
            msg = 'enter your correct password'
    return render(request,'change_password.html',{'msg':msg, 'message':message, 'mess':mess})



def comment(request,idd):
    print(idd)
    oo = Blog.objects.get(id = idd)
    print(oo)
    if request.method == "POST":
        oo = Blog.objects.get(id = idd)
        comment = request.POST['comment']
        object = Comments(comments = comment, user_id = request.session['userid'], blog_id = oo.id)
        print(object)
        object.save()
        return redirect('user:index')
    return render(request,'comment.html')




def view_comment(request,idd):
    o = Blog.objects.get(id = idd)
    obj = Comments.objects.filter(blog_id = o.id)

    return render(request,'view_comment.html',{'data':o,'d':obj})

user/templates/add_blog.html
{% extends 'index.html' %}
{% load static %}
{% block content %}




<div class="row" id="body">
    <div class="col-lg-4"></div>
    <div class="col-lg-4 col-sm-12">
        <div id="head_style" >Add Your Blog</div>
        <div class="center" id="form_body">
            <form action="{% url 'user:add_blog' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row col-100"><div ><input type="text" name="title" id="title" placeholder="title of your blog"></div></div>
                <div class="row col-100"><div ><input type="text" name="subtitle" id="subtitle" placeholder="subtitle of your blog"></div></div>
                <div class="row col-100"><div ><input type="text" name="description" id="description" placeholder="Your blog description"></div></div>
                <div class="row col-100"><div style="width: 225px;"><input type="file" name="image" id="image" placeholder="Upload images"></div></div>

                
                <div class="row">
                    <input id="submit" type="submit" value="POST">
                </div>
                <small>{{mess}}</small>
                
            </form>
        </div>
        

    </div>
    <div class="col-lg-4"></div>
</div>





{% endblock %}

user/templates/change_password.html
{% extends 'index.html' %}
{% load static %}
{% block content %}




<div class="row" id="body">
    <div class="col-lg-4"></div>
    <div class="col-lg-4 col-sm-12">
        <div id="head_style">Change Your password</div>
        <div class="center" id="form_body">
            <form action="{% url 'user:change_password' %}" method="POST" onsubmit="return formvalidation()">
                {% csrf_token %}
                <div class="row col-100"><div ><input type="text" name="current_password" id="current_password" placeholder="Your current password"></div></div>
			    <small>{{msg}}</small>
                <div class="row col-100"><div ><input type="text" name="new_password" id="new_password" placeholder="Your new password"></div></div>
                <small id="password_p"></small>
                <div class="row col-100"><div ><input type="text" name="confirm_password" id="confirm_password" placeholder="Your confirm new password"></div></div>
			    <small>{{message}}</small>

                
                <div class="row">
                    <input id="submit" type="submit" value="change">
                </div>
                <small>{{mess}}</small>
                
            </form>
        </div>
        

    </div>
    <div class="col-lg-4"></div>
</div>


<script>
    function formvalidation(){
        var password = document.getElementById('new_password')
        var password_p = document.getElementById('password_p')

        var lowerCaseLetters = /[a-z]/g;
    	var upperCaseLetters = /[A-Z]/g;
    	var numbers1 = /[0-9]/g;
    	var specialChar = /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/;
       
        status = 0

        if(password == ""){
			password_p.innerHTML = "password should be required"
		}else{
			password_p.innerHTML = ""
		}
        
        
        
        if (password.length < 6 ){
			password_p.innerHTML = "need more than 6 charecters"
			status = 1
		}else if(!password.match(lowerCaseLetters)){
			password_p.innerHTML = "need 1 lowercase letter"
			status = 1
		}else if(!password.match(upperCaseLetters)){
			password_p.innerHTML = "need 1 uppercase letter"
			status = 1
		}else if(!password.match(numbers1)){
			password_p.innerHTML = "need atleast 1 number"
			status = 1
		}else if(!password.match(specialChar)){
			password_p.innerHTML = "need atleast 1 symbol"
			status = 1
		}else{
			password_p.innerHTML = ""
		}


        if (status == 1) {
        	return false
    	}
    }
</script>




{% endblock %}

user/templates/comment.html
{% extends 'index.html' %}
{% load static %}
{% block content %}



<div class="row" id="body">
    <div class="col-lg-4"></div>
    <div class="col-lg-4 col-sm-12">
        <div id="head_style">add Your comment</div>
        <div class="center" id="form_body">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div align="center"><input type="text"  name="comment" placeholder="Add comment to this post"></div>
                </div>
                
                <div class="row">
                    <input id="submit" type="submit" value="done">
                </div>
                
            </form>
        </div>
        

    </div>
    <div class="col-lg-4"></div>
</div>






{% endblock %}

user/templates/edit_profile.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">




<div class="row" id="body">
    <div class="col-lg-4"></div>
    <div class="col-lg-4 col-sm-12">
        <div id="head_style">Edit Your Details</div>
        <div class="center" id="form_body">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-25"><label for="name">Name:</label></div>
                    <div class="col-75"><input type="text"  name="name" value="{{data.user.name}}"></div>
                </div>
                <div class="row">
                    <div class="col-25"><label for="name">Email:</label></div>
                    <div class="col-75"><input type="text" name="email" value="{{data.user.email}}"></div>
                </div>
                <div class="row">
                    <div class="col-25"><label for="name">Username:</label></div>
                    <div class="col-75"><input type="text" name="username" value="{{data.username}}"></div>
                </div>
                <div class="row">
                    <input id="submit" type="submit" value="Update">
                </div>
                
            </form>
        </div>
        

    </div>
    <div class="col-lg-4"></div>
</div>




{% endblock %}

user/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/form.css' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        

        
        
    
</head>

<body>
    <div class="head">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="#">Mini Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'user:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if 'userid' not in request.session %}
                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}">Login</a></li>
                {% endif %}
                
                {% if 'userid' in request.session %}
					      <li class="nav-item"><a href="{% url 'user:add_blog' %}" class="nav-link">Add blog</a></li>
					      <li class="nav-item"><a href="{% url 'user:change_password' %}" class="nav-link">Change Password</a></li>
					      <li class="nav-item"><a href="{% url 'user:edit_profile' %}" class="nav-link">Edit profile</a></li>
					      <li class="nav-item"><a href="{% url 'user:logout' %}" class="nav-link">Logout</a></li>
                {% endif %}
                
              </ul>
            </div>
          </nav>
    </div>

    {% block content %}
    <div class="row">
       <div class="col-lg-12 col-sm-12">
        <div class="front">
          <img src="{% static 'images/img.jpg' %}" alt="" width="100%", height="500px">
          <div class="centered"> <br> hi {{data.user.name}}, <br> welcome to Mini Blog!</div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-12 col-sm-12"></div>
        <div class="col-lg-4 col-md-12 col-sm-12">
          <div id="head_style"><h1 style="font-weight: 700;">  Latest Blogs  </h1></div>
        </div>
        <div class="col-lg-4 col-md-12 col-sm-12"></div>
      </div>
      <div class="row">
      {% for d in objects %}
      <div class="col-lg-4 col-md-6 col-sm-4">      
          <div class="card" style="width: 350px;">
            <img class="card-img-top" src="{{d.image.url}}" alt="Card image cap">
            


              <!-- like portion -->
                  <div class="row like">
                    <div class="col-lg-1"><div class="icon-like" style="margin-top: 20px;"></div></div>
                    <div class="col-lg-2"><a href="{% url 'user:comment' d.id %}"><i class="bi bi-chat  fa-2x" style="margin-left: 5px; color: rgba(0, 0, 0, 0.258);"></i></a></div>
                  </div>
                  <p class="card-text"><a href="{% url 'user:view_comment' d.id %}" style="color: white;">view all comments</a></p>
                <div class="card-body1">
              <h5 class="card-title"><b>{{d.title}}</b></h5>
              <h6 class="card-title"><u>{{d.subtitle}}</u></h6>
              <p class="card-text description">{{d.description}}</p>
            </div>
          </div>
        </div>

                  <!-- Modal -->
<form action="" method="POST">
  {% csrf_token %}
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input type="text" name="comment" id="comment" placeholder="enter comment on this blog...">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button></a>
        </div>
      </div>
    </div>
  </div>
</form>
        {% endfor %}

        <br><br><br>


<!-- modal end -->
  </div>
    </div><br><br><br><br>




    {% endblock %}

    <footer class="footer" style="font-size: 14px;">
      <div class="">
        <div class="container text-center py-5">
          <div class="row">
            <div class="col-lg-4 ">
              <h4 class="font-weight-bold text-left">QUICK LINKS</h4>
              <ul class="text-left py-3">
                <a href="{% url 'user:login' %}" id="example">Login</a><br>
                <a href="#" id="example">Register</a><br>
                <a href="{% url 'user:edit_profile' %}" id="example">Edit Profile</a><br>
                <a href="{% url 'user:change_password' %}" id="example">Change password</a><br>
                <a href="{% url 'user:logout' %}" id="example">Log out</a><br>

              </ul>
  
            </div>
            <div class="col-lg-4 col-md-6">
              <h3 class="font-weight-bold text-left">About Blogs</h3>
              <ul class="text-left py-3">
                <a href="#" id="example">Add blog</a><br>
                <a href="#" id="example">Latest blogs</a><br>
                <a href="#" id="example">Popular blogs</a><br>
                <a href="#" id="example">View your blogs</a><br>
                <a href="#" id="example">View all blogs</a><br>
              </ul>
            </div>
  
            <div class="col-lg-4">
              
              <h3>
                <p class="px-4">Follow Us</p><br><br>

                <span class="mr-4"><i class="bi bi-instagram"></i></span>
                <span class="mr-4"><i class="bi bi-facebook"></i></span>
                <span class="mr-4"><i class="bi bi-twitter"></i></span>
                <span class="mr-4"><i class="bi bi-linkedin"></i></span>
                <span class="mr-4"><i class="bi bi-youtube"></i></span>
              </h3><br>
              <p><a href="#">abcdhospital@gmail.com</a></p> |
              <p><a href="#">about</a></p>
  
  
  
  
  
  
  
            </div>
          </div>
          <hr>
  
          
        </div>
      </div>
  
    </footer>





<script>
  $('.icon-like').on('click', function(){
    $(this).toggleClass('in-like');
  });
</script>

</body>
</html>

user/templates/login.html
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">






<div class="container1" id="container1">
	<div class="form-container1 sign-up-container1">
		<form action="{% url 'user:login' %}" method="POST" onsubmit="return formvalidation()">
			{% csrf_token %}
			<h3>Create Account</h3>
			<span>or use your email for registration</span>
			<input type="text" placeholder="Name" name="Name" id="name" />
			<small id="name_p"></small>
			<input type="email" placeholder="Email" name="Email" id="email" />
			<small id="email_p"></small>
			<input type="text" placeholder="username" name="Username" id="username" />
			<small id="username_p">{{error_msg}}</small>
			<input type="password" placeholder="Password" name="Password" id="password" />
			<small id="password_p"></small>
			<button type="submit" name="u_register">Sign Up</button>
		</form>
	</div>
	<div class="form-container1 sign-in-container1">
		<form action="#" method="POST" >
			{% csrf_token %}
			<h1>Sign in</h1>
			<div class="social-container1">
                <a href="#" class="social"><i class='icon-facebook'></i></a>
				<a href="#" class="social"><i class="icon-google-plus"></i></a>
				<a href="#" class="social"><i class="icon-linkedin"></i></a>
			</div>
			<span>or use your account</span>
			<input type="text" placeholder="username" name="username" />
			<input type="password" placeholder="Password" name="password" />
			<small>{{message}}</small>
			<a href="#">Forgot your password?</a>
			<button type='submit' name="u_login">Sign In</button>
		</form>
	</div>
	<div class="overlay-container1">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome to Mini Blog!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Welcome to Mini Blog!</h1>
				<p>Enter your personal details and start journey with us</p>
				<button class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>



<script src="{% static 'js/login.js' %}"></script>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

<script>
	function formvalidation(){
		var name = document.getElementById('name').value
		var email = document.getElementById('email').value
		var password = document.getElementById('password').value

		var name_p = document.getElementById('name_p')
		var email_p = document.getElementById('email_p')
		var password_p = document.getElementById('password_p')

		var lowerCaseLetters = /[a-z]/g;
    	var upperCaseLetters = /[A-Z]/g;
    	var numbers1 = /[0-9]/g;
    	var specialChar = /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/;
		



		status = 0

		if (name == ""){
			name_p.innerHTML= "name should be required"

			status = 1

		}else{
			name_p.innerHTML = ""
		}
		
		if(email == ""){
			email_p.innerHTML = "email should be required"
			status = 1
		}else{
			email_p.innerHTML = ""
		}
		
		if(password == ""){
			password_p.innerHTML = "password should be required"
		}else{
			password_p.innerHTML = ""
		}
		
		

		
		if (password.length < 6 ){
			password_p.innerHTML = "need more than 6 charecters"
			status = 1
		}else if(!password.match(lowerCaseLetters)){
			password_p.innerHTML = "need 1 lowercase letter"
			status = 1
		}else if(!password.match(upperCaseLetters)){
			password_p.innerHTML = "need 1 uppercase letter"
			status = 1
		}else if(!password.match(numbers1)){
			password_p.innerHTML = "need atleast 1 number"
			status = 1
		}else if(!password.match(specialChar)){
			password_p.innerHTML = "need atleast 1 symbol"
			status = 1
		}else{
			password_p.innerHTML = ""
		}

		if (status == 1) {
        	return false
    	}
	}
</script>
{% endblock %}

user/templates/view_comment.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<style>
    .container{
        color: white;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-sm-12">
        <div>
            <img src="{{data.image.url}}" alt="" width="100%" height="300px">
        </div>
        <h3 style="font-weight: bold;">{{data.title}}</h3>
        <h4>{{data.subtitle}}</h4>
        <hr>
        <p>{{data.description}}</p>
        </div>
        <div class="col-lg-6 col-sm-12">
            <h3 style="font-weight: bold">Comments</h3>
            <hr>
            {% for da in d %}
            <p class="card-text">commented by <b>{{da.user.user.name}}</b></p>
            <p>{{da.comments}}</p>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}